//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRIS_USER
    {
        public decimal USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public byte[] USER_PASSWORD { get; set; }
        public string USER_EMAIL { get; set; }
        public Nullable<decimal> RETRY_ATTEMPTS { get; set; }
        public string USER_STATUS { get; set; }
        public decimal CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public decimal LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> PASSWORD_CHANGE_DATE { get; set; }
        public Nullable<System.DateTime> PASSWORD_EXP_DATE { get; set; }
        public string USER_QUESTION { get; set; }
        public byte[] ENC_DEC_KEY { get; set; }
        public string USER_ANSWER { get; set; }
    }
}
