//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public decimal EMPL_ID { get; set; }
        public string EMPL_TYPE_ID { get; set; }
        public string SERV_CENTER_ID { get; set; }
        public Nullable<decimal> OFFICE_ID { get; set; }
        public string FCO_DESIGN_CD { get; set; }
        public string EMPL_ZIPCODE { get; set; }
        public string EMPL_FNAME { get; set; }
        public string EMPL_MNAME { get; set; }
        public string EMPL_LNAME { get; set; }
        public string EMPL_SSN { get; set; }
        public string EMPL_TITLE { get; set; }
        public string EMPL_SUPERVISOR { get; set; }
        public string EMPL_WORK_PH_NUM { get; set; }
        public string EMPL_HOME_PH_NUM { get; set; }
        public string EMPL_WORK_FAX_NUM { get; set; }
        public string EMPL_EMAIL_ADDR { get; set; }
        public Nullable<System.DateTime> EMPL_DOB { get; set; }
        public string EMPL_MOTHER_NM { get; set; }
        public string EMPL_STATUS { get; set; }
        public decimal USER_ID { get; set; }
        public Nullable<decimal> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string EMPL_UID { get; set; }
    }
}
